### ISSUE TITLE
SaltRenderError: Jinja variable 'dict object' has no attribute 'protocol' 

### ISSUE THREAD

**Issue by michaelkuty** [tcpcloud/salt-formula-jenkins#2]
```
slave:
    ----------
    enabled:
        True
    master:
        ----------
        host:
            localhost
        port:
            8080
    pkgs:
        False
    sudo:
        False
    user:
        ----------
        name:
            admin
        password:
            asdasd645

----------
          ID: /etc/default/jenkins-slave
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1703, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1649, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 1635, in managed
                  **kwargs
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3940, in check_managed_changes
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 3610, in get_managed
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 384, in render_jinja_tmpl
                  buf=tmplstr)
              SaltRenderError: Jinja variable 'dict object' has no attribute 'protocol' 
```

**Comment by Tokix** [comment]
Just ran into a similar issue you need to add the attribute protocol in your jenkins.sls pillar file like so i suspect (you can handle similar errors in the same way): 


jenkins:
  slave:
        master:
      host: jenkins.example.com
      port: 80
      protocol: http

Taken from main page https://github.com/tcpcloud/salt-formula-jenkins/ under "Agent (former slave)"
